### ISSUE TITLE
Init script example

### ISSUE THREAD

**Issue by fuerst** [juhovh/shairplay#11]
Here is in example init script for Debian Wheezy. It expects the _airport.key_ file in _/usr/local/share/shairplay_. May be useful for some of you. 

Install it like this:

* Copy the script to the new file _/etc/init.d/shairplay_
* Make it executable: `chmod +x /etc/init.d/shairplay`
* Configure start/stop at boot/shutdown time: `update-rc.d shairplay defaults`
* Create the _/usr/local/share/shairplay_ directory and copy the _airport.key_ file from the shairplay source to _/usr/local/share/shairplay_. shairplay needs to be started from a directory where it finds the _airport.key_ file.

```bash
#!/bin/bash
#
# This starts and stops shairplay
#
### BEGIN INIT INFO
# Provides:          shairplay
# Required-Start:    $network
# Required-Stop:
# Short-Description: Free portable AirPlay server implementation similar to ShairPort.
# Description:       Free portable AirPlay server implementation similar to ShairPort.
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO


# Source function library.
. /lib/lsb/init-functions

DAEMON="/usr/local/bin/shairplay"
DAEMON_ARGS="-a Wohnzimmer"
AIRPORT_KEY_DIR="/usr/local/share/shairplay"

[ -x $binary ] || exit 0

RETVAL=0

start() {
    echo -n "Starting shairplay: "
    start-stop-daemon --start --quiet --chdir $AIRPORT_KEY_DIR \
                      --exec "$DAEMON" -b --oknodo -- $DAEMON_ARGS
    log_end_msg $?
}

stop() {
    echo -n "Shutting down shairplay: "
    start-stop-daemon --stop --quiet --exec "$DAEMON" \
                --retry 1 --oknodo
    log_end_msg $?
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status shairplay
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
    ;;
esac

exit 0
```

**Comment by juhovh** [comment]
Let's move this to #17 which already has a pretty good example, that might be valid to include in the code base.

**Comment by jmvandamme** [comment]
Hi. 5 years later, I'v got the same issue than @DanielSmedegaardBuus. I manage this issue by adding a "ugly"  sleep 2 in the start() function
`start() {
    echo -n "Starting shairplay: "
    sleep 2
    start-stop-daemon --start --quiet --chdir $AIRPORT_KEY_DIR \
                      --exec "$DAEMON" -b --oknodo -- $DAEMON_ARGS
    log_end_msg $?
}`

I looked for a problem of dependecies in the shairplay init file and tested different dependenices without finding a solution :(
