### ISSUE TITLE
Connecting the Puleaudio through AirTunes destroys Shairtunes

### ISSUE THREAD

**Issue by rubin110** [juhovh/shairplay#12]
I apologize in advance for a bit of a disjointed bug report.

Debian Wheeze 64bit, internal and USB based audio devices through Pulseaudio.

I had Shairtunes running for about 10 minutes, then I wanted to see if Pulseaudio could connect to it through it's own AirTunes option. That made Shairtunes barf. Now when I restart Shairtunes I see...

Could not initialize the RAOP service

For whatever reason I figured the issue might be from avahi being annoyed, restarted the service and turned on some verbose debugging with libao...

$ shairplay --server_port=5019 --ao_deviceid=1
debug: Loaded driver null (built-in)
debug: Loaded driver wav (built-in)
debug: Loaded driver raw (built-in)
debug: Loaded driver au (built-in)
debug: Loading driver plugins from /usr/lib/ao/plugins-4...
debug: Loaded driver nas
debug: Loaded driver oss
debug: Loaded driver pulse
debug: Loaded driver alsa
debug: Loaded driver esd
debug: Testing drivers to find playback default...
ao_alsa debug: Trying to open ALSA device 'hw:1'
ao_alsa debug: Using ALSA device 'hw:1'
Could not initialize the RAOP service

I've rebooted the machine, no dice.

**Comment by zm90125** [comment]
Hey,I'm trying to do this blow:
*********************************************************************************
shairplay-master  shairplay-master.zip
root@qicheng-desktop zhoulee# cd shairplay-master
root@qicheng-desktop shairplay-master# ls
AirTV-Qt     README.md       config.guess  config.status  include     missing
LICENSE      aclocal.m4      config.h      config.sub     install-sh  src
Makefile     airport.key     config.h.in   configure      libtool     stamp-h1
Makefile.am  autogen.sh      config.h.in~  configure.ac   ltmain.sh
Makefile.in  autom4te.cache  config.log    depcomp        m4
root@qicheng-desktop shairplay-master# shairplay
Initialized server socket(s)
*** WARNING *** The program 'shairplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=shairplay>
**********************************************************************************
Open my airplay ,But still can't find my iphone device ,is there any solutions?

**Comment by s9443112** [comment]
me too +1
