### ISSUE TITLE
Playback Progress

### ISSUE THREAD

**Issue by yallah** [juhovh/shairplay#14]
Hi,
I need some feature about time position for sound track. 

I say perhaps completly stupid and wrong (I m not developper) but when I look unofficial docs about airplay ( http://nto.github.io/AirPlay.html ).
I find in metadatapart (in Audio area) Track Informations, Cover Artwork and Playback Progress with :

 Playback Progress

 Playback progress is sent as text/parameters, with a progress parameter representing three absolute RTP timestamps values: start/curr/end.

 timestamp description
 start beginning of the current track
 curr current playback position
 end end of the current track
 The relative position and track duration can be computed as follows:

 position = rtptime_to_sec(curr - start)
 duration = rtptime_to_sec(end - start)
 Example: send playback progress

 client → server
 SET_PARAMETER rtsp://fe80::217:f2ff:fe0f:e0f6/3413821438 RTSP/1.0
 CSeq: 10
 Session: 1
 Content-Type: text/parameters
 Content-Length: 44
 User-Agent: iTunes/10.6 (Macintosh; Intel Mac OS X 10.7.3)
 AppleWebKit/535.18.5
 Client-Instance: 56B29BB6CB904862
 DACP-ID: 56B29BB6CB904862
 Active-Remote: 1986535575

 progress: 1146221540/1146549156/1195701740
 server → client
 RTSP/1.0 200 OK
 Server: AirTunes/130.14
 CSeq: 10

Regards

**Comment by juhovh** [comment]
The change is now merged in a pull request https://github.com/juhovh/shairplay/pull/38
