### ISSUE TITLE
Synchronization and buffer options

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [juhovh/shairplay#16]
Hi :)

I just switched from XBMC's AirPlay feature to Shairplay on my Ubuntu server, so that I can have XBMC play videos to my plasma screen while simultaneously having a working Airplay server to connect to.

Shairplay shows up on my iPad which XBMC's Airplay didn't, so that's cool.
Latency with Shairplay is significantly lower than with XBMC, so that's also really cool, except:

1) I sometimes get the occasional buffer underrun stuttering in the audio stream, which is pretty annoying.
2) The latency is actually so low that whereas XBMC would play the sound *delayed* when I viewed videos on my MacBook, Shairplay will play it one or two seconds *ahead* of the video.

The interesting thing about the second issue is that both my iPad and my MacBook seem to agree about the timing, so I don't know if there's any negotiation going on between the client and the server, where the server reports a wrong delay? Or if it's just some "magic number" that "authorized" Airplay servers are supposed to match... Or maybe it's all random.

In any event, it'd be really helpful if we were able to supply an argument to the Shairplay server in order to set the buffer size so that we could both avoid hiccups in the stream and perhaps be able to synchronize our servers so that we'd get synchronized video and audio playback when streaming audio to Shairplay :)

Cheers,
Daniel :)

**Comment by juhovh** [comment]
This is being worked on in the experimental branch but is not finished yet, the NTP support helps in synchronization.

**Comment by juhovh** [comment]
For more information please see https://github.com/juhovh/shairplay/pull/25 but it will take some time to land on Kodi because of big changes in both ends.

**Comment by DanielSmedegaardBuus** [comment]
I've been battling extreme dropout issues with Shairplay since buying a used NAD DAC 1 USB dongle a couple of months back. My rig went from the sporadic crackling using my built-in audio card to constant crackling and a lot of skipping of anywhere from (what sounds like) 100 ms to 500 ms of audio.

For a while I thought it had to do with the fact that I was using resampling in my alsa config (as the NAD DAC 1 only supports 48 kHz and cannot itself upsample), but today it struck me to try and just play wav files using aplay on the machine, to remove Shairplay from the equation. Playback is now perfect, except for a few massive underruns reported by aplay within the first couple of handful of seconds.

I've tried to install Shairplay on my quad-core main rig, an Android tablet, and a dual-core laptop. Each one of them stutters and breaks horribly with this soundcard (which is driverless and presents itself as a generic USB headset). It is completely useless.

I can't say what it is exactly, or if it would be fixable if given the possibility of fiddling with buffers, but I can say for sure that something is seriously broken in Shairplay... What should I do? Perhaps try compiling it myself with different buffer lengths and see what happens? I'll try to see if I can.

Cheerio :)

**Comment by DanielSmedegaardBuus** [comment]
BTW, I apologize for having ignored you — I don't think I ever saw that reply about a year ago. I'm testing out a build with `RAOP_BUFFER_LENGTH 64` and `buffer[65536]` right now.

**Comment by DanielSmedegaardBuus** [comment]
It took only a couple of minutes, now it's starting to skip/crackle. Streaming to Shairplay always starts out fine after having initialized a stream and then it gets progressively worse. That's why I was thinking it had to do with the resampling... It "felt" like some kind of clock drift, if that's even an applicable term here. I'm gonna try some much more aggressive settings. If there are upper limits on the buffers, I guess I might soon find them ;)

**Comment by DanielSmedegaardBuus** [comment]
Also skipping after a couple of minutes with `RAOP_BUFFER_LENGTH 128` and `buffer[131072]`. ATM, fallouts of about 200 ms.

**Comment by DanielSmedegaardBuus** [comment]
Can I enable some kind of debug mode?

**Comment by DanielSmedegaardBuus** [comment]
With this setting, and the previous one, though, they both seemed to recover a bit after the initial problems after a few minutes. Gonna try 256/256*1024 now.

**Comment by juhovh** [comment]
I'm working on refactoring the output to a separate thread so that output blocking wouldn't cause glitches in the network side. It's not done yet but the result should be somewhat similar to what is done at https://github.com/foxsen/shairplay, you could give it a try if you wish but it also depends on AAC decoder.

**Comment by DanielSmedegaardBuus** [comment]
Do you think that's what happens here? Does that make sense with the fact that the stuttering is worse on this new audio output compared to the old on-board one? I think this audio card is more buffer sensitive that my old one. And, in the meantime, is there anything I can do as a workaround until this feature makes it into master? Thanks man :)

FTR, so far it seems that 256/256*1k is somewhat more stable than the previous settings. I have a couple of slight stutters just now, but so far they're minor. I think I'll try a ridiculously large buffer and see how it fares.

PS: Now that you say it, I think you're right that something might be sensitive on the network side — streaming from my Air is somewhat better than streaming via AirAudio on an Android device.

PS2: While writing this, the stream is now becoming useless again :/ Lots of crackling, starting to skip large bits of audio. The buffer on the sender is 2.5 seconds...

**Comment by DanielSmedegaardBuus** [comment]
FYI: Thinking that it might be an issue with ALSA and resampling, I've actually set up my current system so that one core is off-limits for the CPU scheduler on launch, and I'm running just Shairplay on this second core, in an attempt to prevent other processes from blocking it.

**Comment by DanielSmedegaardBuus** [comment]
Hehe, I think `RAOP_BUFFER_LENGTH 1024` and `buffer[1048576]` might be pushing it a bit :D It took a second or two when starting the stream of "Buffering..." outputs in the terminal, and it skipped heavily in the very start. But let's see. I'm gonna use this for a while and report back.

**Comment by DanielSmedegaardBuus** [comment]
Okay, those settings gave me about ten minutes of almost stutterfree playback, and then the problems came back with a vengeance. Just tried streaming from my Mac, and it seems Apple *really* don't like those buffer settings, as volume changes take many seconds to be registered (weird that AirAudio could control audio with much much lower delay), and every three seconds I get a two-second sound break... Gonna try a couple more combos before giving up :)

**Comment by DanielSmedegaardBuus** [comment]
It's funny... I'm now playing Spotify from my Mac at `RAOP_BUFFER_LENGTH 1024` and `buffer[16384]`. This combo is working *very very* well so long as I go about my normal work, including surfing the net and having a virtual machine uploading files to LiveDrive. I have just about zero interruptions so long as I don't do anything "explicitly" network-related. Simply clicking on the wifi icon to view options will cause stutters in the audio. Every time. Click, wait some hundreds of a milisecond, and audio will stutter. This puzzles me, because it seems like the "local" cache of samples to the soundcard on Shairplay's side doesn't matter as much as interruptions to the net stream does — any slight packet interruption causes audio interruptions, even if my buffer is a megabyte. Am I making sense? It seems like Shairplay is overly sensitive to network dropouts even when it ought to have a buffer large enough to ignore those? I even have specific events I could do on my Mac that had to do with networking to crash Shairplay without even being connected to it. Of course, being an idiot, now I don't remember them, as they were some months back, but it was very reproducible... Could the problem lie somewhere else, such as the bonjour library? Or? Just talking out of my ass here.

Either way, even with the dropouts as described above, my Mac so far seems 99% skip-free if I don't click the wifi icon @ `RAOP_BUFFER_LENGTH 1024` and `buffer[16384]`.

**Comment by DanielSmedegaardBuus** [comment]
Hmmmm... I tried to freak out Shairplay, but now I'm not sure if it's my clicking the wifi icon or a USB drive being indexed, but I now have about three seconds of audio interrupted by three seconds of silence with Shairplay....
