### ISSUE TITLE
Can't connect to ShairPlay when backgrounding it or opening it via init.d

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [juhovh/shairplay#17]
Hi :)

I tried the init.d example script posted here (minor mods), and discovered that it'll start and stop shairplay correctly — I can see the process running with the right arguments — but I won't be able to connect to it from my MacBook (It still shows up on the network, though, selecting it just does nothing).

If I stop the service and start shairplay in a shell manually with the exact same arguments, it'll work perfectly.

The same problem arises if I use that same shairplay shell command, but background it with '&'. It'll run, but I won't be able to connect.

I also don't see the usual stdout log, so I'm thinking perhaps there's some bug in shairplay that surfaces when it no longer can write to an interactive terminal?

Cheers,
Daniel :)

**Comment by cyberhiker** [comment]
I was having similar issues.  I've posted my ```/etc/init.d/shairplay``` and ```/etc/default/shairplay``` here: https://gist.github.com/cyberhiker/9b60b1115e250a597c3f

**Comment by juhovh** [comment]
Unfortunately these are a bit outdated since everything is systemd now...
