### ISSUE TITLE
Running shairport with isc-dhcp-server (adhoc)

### ISSUE THREAD

**Issue by bryan092785** [juhovh/shairplay#27]
I've installed isc-dhcp-server and configured an adhoc network over wireless to use shairport in instances that I'm not near a wifi router. When on the ad hoc network my ios device is not seeing shairport. Is there any information on how to get this working? Please advise, any info in the right direction is much appreciated

**Comment by juhovh** [comment]
This is not really a shairplay issue but rather related to avahi or whatever mDNS is used on the system. Shairplay itself should be broadcasting to all interfaces and work on the link layer IPv6 addresses as well, so it shouldn't be a problem. But if you have more information feel free to reopen.
