### ISSUE TITLE
Unable to get video over shairplay

### ISSUE THREAD

**Issue by napentathol** [juhovh/shairplay#39]
Hi,

I installed this, and I'm able to get audio over it, but I am not able to get video.

I ran all the commands under the Installation header to install it, and I started up the service with `shairplay -a comp` is there a configuration step I'm missing?

thanks

**Comment by juhovh** [comment]
As said on the main page "Currently only AirPort Express emulation is supported.", and AirPort Express doesn't support video. However, the mirroring is finally under work and possibly there will be some simple support for normal video as well. Just need to be patient to get this right.
