### ISSUE TITLE
shairplay: shairplay.c:170: audio_init: Assertion `session->device' failed.

### ISSUE THREAD

**Issue by gonzojive** [juhovh/shairplay#40]
Here's a crash log:

```
Handled request OPTIONS with URL *
Receiving on socket 13
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record
Responding with RTP/AVP/TCP;unicast;interleaved=0-1;mode=record;server_port=39637
Handled request SETUP with URL rtsp://192.168.86.145/1793989254
Receiving on socket 13
Handled request RECORD with URL rtsp://192.168.86.145/1793989254
Receiving on socket 13
Handled request SET_PARAMETER with URL rtsp://192.168.86.145/1793989254
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
Error opening device 5
shairplay: shairplay.c:170: audio_init: Assertion `session->device' failed.
```

**Comment by simonvetter** [comment]
I'm also seeing this on latest master (https://github.com/juhovh/shairplay/commit/498bc5bcdd305e04721f94a04b9f26a7da72673f)

Fairly easy to reproduce:
1) stream from one device (e.g. iphone) to a shairplay sink
2) from another device (e.g. macbook), try to stream to the same shairplay sink

I think the proper way of handling this would be to report that the audio device is already in use.

(still odd to me that a dmix sink would fail to mix two different streams as iirc that's what dmix is for, but I'm seeing the same behaviour on my setup.)

**Comment by juhovh** [comment]
I made a quick fix to master, it still doesn't reject the new client but it will simply not play the audio. Not the prettiest solution but should fix this, let me know if it did.

**Comment by simonvetter** [comment]
I can confirm that the fix prevents shairplay from crashing.
Thanks!
