### ISSUE TITLE
Document dependencies?

### ISSUE THREAD

**Issue by mathewpeterson** [juhovh/shairplay#44]
I was trying to compile this on my Raspberry Pi B and had to compile [fdk-aac](https://github.com/mstorsjo/fdk-aac) and [libplist](https://github.com/Chronic-Dev/libplist) from source.

**Comment by mathewpeterson** [comment]
Hm, sorry. I suppose this is only for the https://github.com/foxsen/shairplay fork.

**Comment by juhovh** [comment]
That is correct, although they might be necessary in the future but I will update documentation then.
