### ISSUE TITLE
iOS9 - some progress!

### ISSUE THREAD

**Issue by hay187** [juhovh/shairplay#48]

**Comment by kam187** [comment]
I forgot to mention these tests are done with epes: https://github.com/espes/Slave-in-the-Magic-Mirror

It's just an easy way to try stuff quickly.

**Comment by jvah** [comment]
I saw your messages, did the current master with GET_PARAMETER help?

**Comment by kam187** [comment]
Unfortunately not really.

It seems the encoding is different now too.  I've managed to get a key for a logged session by debugging a commercial solution and am trying to see if I can figure it out from there.

**Comment by kam187** [comment]
Some more progress, see bottom of here:

https://github.com/espes/Slave-in-the-Magic-Mirror/issues/12

If anyone can help figure out the decryption let me know!  The key should be 100% correct.

**Comment by kam187** [comment]
Found a airtunesd with the new encryption :)  See the issue above.

**Comment by juhovh** [comment]
I guess this is a bit outdated, closing.
