### ISSUE TITLE
fairplay.c:51: undefined reference to `closesocket'

### ISSUE THREAD

**Issue by usamitysam** [juhovh/shairplay#49]
New install on Ubuntu 14.04.3 LTS

fairplay.c:51: undefined reference to `closesocket'
during make

Added #include "sockets.h" to fairplay.h and the error went away.  Not sure that this is the correct fix because I have other newbi problems.

**Comment by juhovh** [comment]
Sounds like a correct fix, but I assume this is not the master branch. The other branches would need cleaning up before they are merged to master anyway, so closing it for now.
