### ISSUE TITLE
iOS doesn't discover AirPort on raspberry

### ISSUE THREAD

**Issue by danashevskiy** [juhovh/shairplay#62]
I'm launching shairplay on raspberry pi from source directory with airport.key located in it.

`Initialized server socket(s)
*** WARNING *** The program 'shairplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=shairplay>`

And that's all. Then i take an iPad with iOS 9.3.1 and go to control panel where i can't locate raspberry airport. Devices use the same wifi network (router - Asus WL-520GU). Linux Kernel release - 4.1.7.
I'm not an expert in networking, so have i missed something?

**Comment by tewe** [comment]
I get the same message and discovery from iOS works fine, as well as playback from iTunes. So that's unrelated.

**Comment by ioangogo** [comment]
This is more to do with the fact that this program is using a deprciated api to do what it needs to do

**Comment by Lerentis** [comment]
have you installed avahi?
i had to install avahi and then start avahi-daemon (systemctl enable avahi-daemon && systemctl start avahi-daemon) to see it on my device. after that it just worked fine

**Comment by cloudswave** [comment]
i have the same problem！

**Comment by juhovh** [comment]
The iOS discovery is sometimes a bit flaky, try disconnecting from WiFi with both devices and then try again, sometimes it works sometimes it doesn't.
