### ISSUE TITLE
How can I upgrade openwrt chaos calmer's shairplay version to latest commit?

### ISSUE THREAD

**Issue by manjuprajna** [juhovh/shairplay#64]
I am using shairplay on openwrt chaos calmer 1505, the Makefile is like below:
PKG_NAME:=shairplay
PKG_VERSION:=2014-10-27
PKG_RELEASE:=2

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=git://github.com/juhovh/shairplay.git
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_VERSION:=64d59e3087f829006d091fa0d114efb50972a2bf
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION).tar.gz
PKG_MAINTAINER:=Álvaro Fernández Rojas <noltari@gmail.com>

how can I modify it to latest commit? and there is 3 patch file:
001-key_file_dir.patch, 002-libavahi-compat-dnssd.patch, 003-fix_big-endian.patch
do I have to modify these?

thank you!

**Comment by juhovh** [comment]
I have no idea about openwrt unfortunately.
