### ISSUE TITLE
airplay.h missing & Qt problem

### ISSUE THREAD

**Issue by AhmedX6** [juhovh/shairplay#66]
Hello,

I'm trying to compile your main.c in /test folder.
But "airplay.h" is missing. Any solution ?
I would like to try the AirPlay Mirror.
Also, I noticed that AirTV-QT is based on Qt4 (it's deprecated now). Is it possible to have it on Qt5 ?

Thank you !

**Comment by juhovh** [comment]
I should probably remove the AirTV from the repo since it is unmaintained, but on the other hand I would like to get screen sharing work at some point. Anyway, marking this as wontfix for now, although it's kind of valid.
