### ISSUE TITLE
Cannot Launch Up

### ISSUE THREAD

**Issue by CarterJimmy** [juhovh/shairplay#68]
I tried to install it into raspberry-pi (Model Raspberry-Pi 2-B)(OS is Kali-Linux). I installed it, but when i tried to launch it up, it said "Please check your libao settings and try again". I tried to reinstall all the contents and reboot, but it doesn't work. Could do tell me what should I do with this problem.
![2017-07-31 0 20 49](https://user-images.githubusercontent.com/7923743/28754717-7036f8d0-7586-11e7-82f0-2eef2622691a.png)

**Comment by dolohow** [comment]
You need to specify `default_driver` and `dev` in `/etc/libao.conf`

If you are using pulseaudio and sink number 0, then it would be
```
default_driver=pulse
dev=0
```

**Comment by CarterJimmy** [comment]
Thx, I will try so. If I got any other question, I will come back again.

**Comment by k-rock** [comment]
I receive a similar error when I start shairplay: I receive this error:
Error opening audio device 5
Please check your libao settings and try again

Could you please advise?
