### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by medapayne** [juhovh/shairplay#69]
Hello

I wanted to know if an update to Airplay 2 was planned?
thank you for your comeback

**Comment by wowton** [comment]
I have same question, thank you. @juhovh

**Comment by juhovh** [comment]
I would like to know what Airplay 2 means in this context? What features?

**Comment by juhovh** [comment]
I kind of hate it when a question is replied with a 30+ minute video that doesn’t answer the question. What Apple advertises as Airplay 2 seems to be mostly client library changes and better buffering and sync support on the server side. While I agree that buffering and sync should be improved, I must aske again: what does Airplay 2 mean in this context?

**Comment by juhovh** [comment]
I'm closing this issue since there doesn't seem to be actual difference with Airplay 1 and Airplay 2. About multi-room I should read through https://github.com/mikebrady/shairport-sync and see what's done there, but I don't expect anything revolutionary.

**Comment by mansidak** [comment]
Hey @juhovh , yeah I had the same question and wanted to enquirer about 'multiroom audio' to be specific. Any chance you ended up studying Mike's repo?
