### ISSUE TITLE
You recent commit break compilation

### ISSUE THREAD

**Issue by phirsov** [juhovh/shairplay#70]
Commit https://github.com/juhovh/shairplay/commit/71b45f8a5ede847fd6aa176d0c550e587b79a3d9 break compilation. Assume, `USE_LIBDL` macro is not defined, AND ( `HAVE_LIBDL` is not defined,  OR `__APPLE__` is defined ). Then, `#if defined(WIN32) || USE_LIBDL` cause pre-processor error because pre-processor `||` operator right-hand operand is not defined. Solution? Simple:

```
#if defined(HAVE_LIBDL) && !defined(__APPLE__)
#define USE_LIBDL 1
#else
#define USE_LIBDL 0
#endif
```

Best regards

**Comment by juhovh** [comment]
Should be fixed now.
