### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by lunamanuel** [juhovh/shairplay#71]
My Rpi2 shows me the following bug as soon as I connect:

```
Accepted IPv4 client on socket 10
Receiving on socket 10
Segmentation fault
```

Is this known? Earlier versions worked like a charm! Thanks

**Comment by juhovh** [comment]
Thank you for your report!
I added an optional fairplay support and forgot to test without it enabled, the change triggered an old bug resulting in a crash. Should be fixed now.
