### ISSUE TITLE
I want to get your code of airplay mirror for a fee. Can you provide it

### ISSUE THREAD

**Issue by CMerlin** [juhovh/shairplay#76]

**Comment by idoo** [comment]
Please take a look to source

**Comment by juhovh** [comment]
All I have is in this repository, I don't have any secret code that I'm trying to sell. Sponsoring development is welcome, but comes with no guarantees. Getting airplay mirroring to work should be doable, at least for iPhone devices if macOS is not required, but I haven't had time to work on it recently.
