### ISSUE TITLE
How I can contact you by email?

### ISSUE THREAD

**Issue by Neustradamus** [juhovh/shairplay#85]
@juhovh: How I can contact you by email?

Can I have your email address?

You can remove this ticket after sending the reply ^^

Thanks in advance.

**Comment by Neustradamus** [comment]
@juhovh: Can you reply me?

**Comment by juhovh** [comment]
Sorry for the delay, each git commit in the repository has the email of the relevant author. Hope this helps.

**Comment by Neustradamus** [comment]
@juhovh: It is not published: https://github.com/juhovh/shairplay/commits/master
No sign-off.

Can you reply me and remove this ticket after?

Thanks in advance.
